### PR TITLE
Fix Broken Test Cases for InputFilterList Implementation

### PR DESCRIPTION
**Pull request by LakeLab**
- Modified test cases that were failing due to the introduction of InputFilterList.
- Ensured test cases reflect the updated behavior and functionality.
- Verified all tests pass to maintain code integrity and functionality.

Related to PR #657

### CODE REVIEW

**Comment by LakeLab** [comment]
The issue with the test cases failing seems to have been resolved with the updated version of this PR. However, the “Test and Analyze” stage is still not passing 🤔 . Specifically, it seems that the Sonar stage is unable to generate the report for some reason, though I’m not sure why.

**Comment by LakeLab** [comment]
It seems like there might be some authentication issues. Could you help @MCMicS !?
Thank you!

**Comment by MCMicS** [comment]
Authentication issues?
You mean during runtime in IDE?
Depends which error I can help

**Review by MCMicS — APPROVED** [review]

**Comment by MCMicS** [comment]
I merged it. It sometimes fails because the secrets could not be read if from pull request other then me or trusted member to protect the secrets

**Comment by MCMicS** [comment]
Now it seems to run. I also changed the checked platform to test against to latest which is currently 243

**Comment by LakeLab** [comment]
> Authentication issues? You mean during runtime in IDE? Depends which error I can help
> 
> Or you mean the broken action in GitHub. I will later to this

I meant the broken action in Github!

> I merged it. It sometimes fails because the secrets could not be read if from pull request other then me or trusted member to protect the secrets

I get it! Thank you!

**Pull request merged**
