### PR TITLE
add open allure report page

### PR DESCRIPTION
**Pull request by AlexanderMacakov**

### CODE REVIEW

**Comment by AlexanderMacakov** [comment]
thanks

**Comment by MCMicS** [comment]
to you have a sample jenkins to test it?

I've test against `https://ci.qameta.io/job/allure-plugin/job/master/lastSuccessfulBuild/` but the URL is not `https://ci.qameta.io/job/allure-plugin/job/master/lastSuccessfulBuild/Allure_Report/` but `https://ci.qameta.io/job/allure-plugin/job/master/lastSuccessfulBuild/allure/` works

Also it is possible to check if allure is avaialbe so that only this options is available if it is possible

**Comment by MCMicS** [comment]
also installed it at my local machine but the url seems wrong.

**Comment by MCMicS** [comment]
Please change the URL and push it again.
thanks for the contribution

**Comment by MCMicS** [comment]
@AlexanderMacakov Is it ok to use URL `<url>/allure`

**Pull request merged**
