### PR TITLE
Dynamic Plugin for 2020.3

### LINKED ISSUE #181: Change to Dynamic Plugin
Starting with 2020.1 release, the ability to install, update and uninstall plugins without restarting the IDE is available in the IntelliJ Platform.

We should change some code to get this working.

http://www.jetbrains.org/intellij/sdk/docs/basics/plugin_structure/dynamic_plugins.html

### PR DESCRIPTION
**Pull request by MCMicS**
resolve #181 Change to Dynamic Plugin for >=2020.3

### CODE REVIEW

**Comment by GoBigorGoHome** [comment]
Tested on 2020.3, uninstall still needs a restart.

**Comment by MCMicS** [comment]
Yes its currently needed because sometimes a reference to a class  is kept.

**Comment by GoBigorGoHome** [comment]
> Yes its currently needed because sometimes a reference to a class is kept

What doest that mean? Can you please elaborate a bit? I am trying to make my plugin dynamic, and has had the same problem as in issue 181.

**Comment by MCMicS** [comment]
If you create a memory dump i last saw a reference from swing panel. I can have help more after holidays

**Comment by MCMicS** [comment]
Sorry for delay.
If you enable memory dump and try to uninstall your plugin a dump is created in your user home. this could be open with IDEA or any other memory dump tool to analyze the  problem. Besides the dump an message will created in your IDE (if you debug from IntelliJ for example)

```
runIde {
    jvmArgs = ['-XX:+UnlockDiagnosticVMOptions']
    systemProperty('ide.plugins.snapshot.on.unload.fail', 'true')
    systemProperty('ide.plugins.allow.unload.from.sources', 'true')
}
```
more info: https://plugins.jetbrains.com/docs/intellij/dynamic-plugins.html#diagnosing-leaks

What plugin is yours. maybe I can also have a look at it to help to identify the cause.

**Comment by MCMicS** [comment]
see #265

**Comment by MCMicS** [comment]
Note: If you Debug your plugin auto reloads / uninstall will mostly fail. Try Run instead of Debug

**Pull request merged**
