### PR TITLE
Wrap content in a JScrollPane

### LINKED ISSUE #558: Add scrolling for jobs with a lot of parameters
Our jobs have a lot of parameters and they don't fit the whole screen, therefore we need scrolling in the build job (parameters) view.

### PR DESCRIPTION
**Pull request by muliyul**
Fixes #558

### CODE REVIEW

**Comment by MCMicS** [comment]
Thanks for Request
I would suggest to remove the border from panel again

grafik

**Comment by MCMicS** [comment]
with border `empty` it looks correct 🤷🏻‍♂️

**Comment by muliyul** [comment]
@MCMicS what are the conditions for the next release?

**Comment by MCMicS** [comment]
I test currently and try to release a new version the next days

**Comment by MCMicS** [comment]
@muliyul EAP is uploaded and can be found here: https://plugins.jetbrains.com/plugin/6110-jenkins-control/edit/versions/eap/478361

**Comment by muliyul** [comment]
Great! What's the timeline for a full release?

**Comment by MCMicS** [comment]
I hope at weekend. I schedule it for sunday

Hope its ok? But you can use EAP as well

**Comment by muliyul** [comment]
Yes no problem.

**Comment by muliyul** [comment]
@MCMicS I've never used EAP before. When a full release is made do I get an update the same way automatically?

**Comment by muliyul** [comment]
Future readers - you can add the EAP repository (https://plugins.jetbrains.com/plugins/eap/list) in your plugin repository settings.

**Comment by MCMicS** [comment]
> @MCMicS I've never used EAP before. When a full release is made do I get an update the same way automatically?

Yes update will be then automatically

**Pull request merged**
